### ISSUE TITLE
Direct search using Ruby notation doesn't link to right page

### ISSUE THREAD

**Issue by tadman** [rubyapi/rubyapi#101]
When searching for something simple, like [`String#length`](https://ruby-api.org/2.6/s?q=String%23length&utf8=✓), you get incorrect results:

![Screen Shot 2019-06-11 at 7 49 22 PM](https://user-images.githubusercontent.com/6184/59314254-7fd7d880-8c82-11e9-99eb-b80919e02734.png)

The example given is `str.length` in the [actual documentation](https://ruby-api.org/2.6/o/string#method-i-length) so is this a searching issue caused by not recognizing the Ruby notation with `#`?

**Comment by colby-swandale** [comment]
Nice find 👍 We should optimise ElasticSearch for these style of search queries

**Comment by colby-swandale** [comment]
I've added this in https://github.com/colby-swandale/rubyapi/commit/0a489a56c254ffbeeb9ee99382b3c05d8db94fbe

**Comment by colby-swandale** [comment]
Hi! Sorry for the long wait in responding to this. I have updated the search engine to favor exact matches for queries like `String#length` very highly.

Searching for methods like `String#length` will now return the documentation for that method as the first result.

I will mark this as completed but let me know if you have any more feedback.

Thank you for helping RubyAPI!
