### ISSUE TITLE
Merge this with official Rubydocs

### ISSUE THREAD

**Issue by rvalenciano** [rubyapi/rubyapi#1113]
First, thank you very much for this effort, it is kindly appreciated!

I was talking with [Aaron Patterson](https://github.com/tenderlove) during RailsConf that it would be great to improve ruby official docs with exactly some of the ideas presented here.

Wondering if we can start any kind of conversation with the official ruby site maintainers?

**Comment by colby-swandale** [comment]
Thank you for your kind words; it's appreciated! ✨

I'm hoping there will be conversations in the future with the ruby-src team to discuss if there's an opportunity to add any functionality from Ruby API into the ruby docs. I'm keen to speak or attend RubyKaigi this year and talk to some of the docs.

Thank you for your kind feedback again.
