### ISSUE TITLE
Fix bin/dev

### ISSUE THREAD

**Issue by natematykiewicz** [rubyapi/rubyapi#1136]
I just saw this PR. https://github.com/rails/jsbundling-rails/pull/113

We should update our `bin/dev` file accordingly.

**Comment by AlexWayfer** [comment]
I was ready to try to help here, but:
1. I see no `bin/dev` file.
2. I see no `foreman` mentions in our project.

Can you explain please what the meaning of this issue?

**Comment by natematykiewicz** [comment]
Lines 3 and 7. https://github.com/rubyapi/rubyapi/blob/main/bin/dev#L7

**Comment by AlexWayfer** [comment]
> Lines 3 and 7. https://github.com/rubyapi/rubyapi/blob/main/bin/dev#L7

My bad, I forgot about fork and it was pretty obsolete. Looking in some issues, including this one!

**Comment by AlexWayfer** [comment]
Should we do something with adjacent `overmind`? There is the same `command -v`.

**Comment by natematykiewicz** [comment]
Yeah, I think so. Overmind doesn't have a `version` command, but it does have a `-v` flag.

```
$ overmind -v
Overmind version 2.2.2
```

**Comment by AlexWayfer** [comment]
> Yeah, I think so. Overmind doesn't have a `version` command, but it does have a `-v` flag.
> 
> ```
> $ overmind -v
> Overmind version 2.2.2
> ```

Honestly, there was an issue with Ruby gem (and shims), as `foreman` is it, and I see that `overmind` is not a gem (in our bundle). Yes. it's written in Go.
