### ISSUE TITLE
Replace slim with erb & view components

### ISSUE THREAD

**Issue by colby-swandale** [rubyapi/rubyapi#1156]
Slim was an attempt to wrangle large amounts of ERB, but it's apparent this was a wrong decision from me, as the value of using slim is not present as we have the same problems.

We should revert to ERB and investigate View Components in the future.

**Comment by natematykiewicz** [comment]
Is there something wrong with Slim, or is it just that there's a learning curve compared to ERB?

View Components are pretty awesome. I've used them a little bit.

**Comment by colby-swandale** [comment]
> Is there something wrong with Slim

Having HTML tags on multiple lines is technically possible in SLIM, but it's a real pain. There is also the extra element of needing to learn a new template language.

**Comment by natematykiewicz** [comment]
Ahh, yeah. And tailwind by nature results in super long lines. Well another positive about switching to ERB is that Byroot has been optimizing ERB rendering between some ActionView changes, and String#append changes. I'm not sure if HAML and Slim will see any benefit from those optimizations. His benchmarks have all been about ERB.

**Comment by AlexWayfer** [comment]
I like ERB more, TBH. Like… more native (raw) language is simpler to move between projects/languages/etc. and understand and work with front-end devs.
