### ISSUE TITLE
Gemified stdlib libraries missing

### ISSUE THREAD

**Issue by rongcuid** [rubyapi/rubyapi#1207]
Libraries from stdlib that is gemified are no longer available in rubyapi.org.

**Comment by colby-swandale** [comment]
Ah, thank you for letting us know! I will look into this promptly.

**Comment by natematykiewicz** [comment]
@colby-swandale, did you ever re-run the importer after I merged https://github.com/rubyapi/rubyapi/pull/1200?

**Comment by colby-swandale** [comment]
dev import is automatically run every 6 hours

**Comment by natematykiewicz** [comment]
What I fixed wasn't specific to dev. It just downloads the gemified gems. So I think you simply need to reimport Ruby 3.0 and 3.1.

**Comment by colby-swandale** [comment]
Ah i understand! No i don't believe i have run the import since that PR. I will do that now 🙇🏻

**Comment by colby-swandale** [comment]
I believe this has been resolved, @rongcuid can you confirm the documentation you were looking for is now on rubyapi.org?

**Comment by rongcuid** [comment]
I think they are online.

**Comment by coffeejunk** [comment]
I think this regressed. For example, I can find `matrix` for 2.7: 

<img width="1177" alt="Screenshot 2022-12-09 at 7 57 22 PM" src="https://user-images.githubusercontent.com/205556/206820548-fffe078a-6bbe-4edf-8cbd-04d2b4411b82.png">

but not for 3.1 or 3.2
<img width="1072" alt="Screenshot 2022-12-09 at 7 57 36 PM" src="https://user-images.githubusercontent.com/205556/206820563-9c5ff38b-752b-47ee-9222-afa4b64492cb.png">

**Comment by colby-swandale** [comment]
@coffeejunk Having a closer look at this I suspect there's something else going on as I'm unable to find `Matrix` on  the official docs either. https://docs.ruby-lang.org/en/3.1

**Comment by colby-swandale** [comment]
I've created #1323 to track this.
