### ISSUE TITLE
Migrating from Cloudflare to Fastly

### ISSUE THREAD

**Issue by colby-swandale** [rubyapi/rubyapi#1245]
I am currently moving the CDN network from Cloudflare to Faslty. This process has already started and may cause some interruption, which i apologise for. I will provide a status update once i have completed the migration.

**Comment by natematykiewicz** [comment]
I've never used Fastly. Any reason you prefer it over Cloudflare?

**Comment by colby-swandale** [comment]
I no longer wish to give Cloudflare my money as their policies no longer align with our Code of Conduct. Please see https://twitter.com/lizthegrey/status/1566196630335922179 for a better explanation.

**Comment by colby-swandale** [comment]
Update: Almost everyone has now moved over to Flastly. I can still see 1 or 2 hits on Cloudflare, but i'm expecting we should be 100% migrated in the coming next few days.

**Comment by colby-swandale** [comment]
This has now completed. Closing.
