### ISSUE TITLE
Switching between Ruby versions sometimes doesn't affect search results

### ISSUE THREAD

**Issue by janko** [rubyapi/rubyapi#1273]
Steps to reproduce:

1. open https://rubyapi.org for Ruby 3.1
2. switch to Ruby 2.7 via the version picker
3. search for `Array#to_h`
4. `Array#to_h` result item will link to the Ruby 3.1 version

https://user-images.githubusercontent.com/795488/201904161-82528972-7f84-4da5-be21-9461c77d32ff.mov

**Comment by colby-swandale** [comment]
Oh nice find! Let me quickly investigate what's happening.

**Comment by colby-swandale** [comment]
@janko I've pushed https://github.com/rubyapi/rubyapi/commit/07e77b2854bd7c10589bc65f01d9a5aa8eaa8388 that should resolve this issue. Can do you do a quick test and let me know if this is working now? (Best to clear browser cache if you are still seeing the same problem)

**Comment by janko** [comment]
Yes, it works correctly now, thanks for the quick fix! ❤️

**Comment by colby-swandale** [comment]
Perfect! Thank you again for the bug report and for your help making Ruby API better!
