### ISSUE TITLE
Theme selection does not appear to be respected

### ISSUE THREAD

**Issue by BytewaveMLP** [rubyapi/rubyapi#1283]
Following the merge of #1271, the site no longer appears to reflect my selected theme, instead always loading in light mode (with the exception of the main page at https://rubyapi.org, which loads in my system theme and does NOT have the theme selector). I can see the cookie being set correctly, however the page does not appear to reflect it, and the dropdown always shows the `System` theme as active no matter which option is actually chosen. Furthermore, despite `System` being selected, the light theme always seems to be served regardless of system preferences.

## Environment

- OS: macOS Ventura 13.0.1
- Browser: Mozilla Firefox 107.0, Google Chrome 107.0.5304.110

**Comment by BytewaveMLP** [comment]
Actually, it looks like this was potentially fixed in 49c5f56062a7feed7055a02b47cdb403c71663fc. Has that just not been deployed?

**Comment by natematykiewicz** [comment]
From what I can tell, changing the theme posts to `/set_theme` with no parameters. Then redirects back with "System" chosen.

<img width="1402" alt="Screen Shot 2022-11-22 at 2 29 50 PM" src="https://user-images.githubusercontent.com/5104186/203415010-01cb28c0-b65d-4792-9302-92b6e523170c.png">

**Comment by natematykiewicz** [comment]
Oh I see. It sets "theme=dark" when I choose dark.

<img width="1402" alt="Screen Shot 2022-11-22 at 2 32 38 PM" src="https://user-images.githubusercontent.com/5104186/203415464-12cbfdb5-03a6-42a2-a5f2-0d88a936f305.png">

<img width="1402" alt="Screen Shot 2022-11-22 at 2 32 41 PM" src="https://user-images.githubusercontent.com/5104186/203415489-a023f7ae-cbbb-4e34-8fe5-a62038748cee.png">

**Comment by glaszig** [comment]
firefox dev edition, 108b3. disrespects "system" setting. system setting for me is dark. but i see the light theme.

**Comment by natematykiewicz** [comment]
I see that as well in Safari. It says it's system, but all I see is light.

**Comment by natematykiewicz** [comment]
I notice that if I change the `"system"` class on the `html` to `"dark"`, it does go dark. Though the header is also the wrong color now, which is something I had previously fixed. It used to make the header of Safari blend in with the top elements on the site.

<img width="1840" alt="Screen Shot 2022-11-22 at 3 14 24 PM" src="https://user-images.githubusercontent.com/5104186/203422691-8906da19-d82c-4a43-83bd-61d959549c05.png">

**Comment by colby-swandale** [comment]
Many apologies for breaking the theme experience 🙇🏻 . I see where i have messed up, I have TailwindCSS set to use dark mode using the `class="dark"` toggle, which works if you explicitly set for dark mode. But for system mode i'm obviously not doing that same check (not sure if i even can with Ruby).


I will revert my changes. Apologies again.

**Comment by natematykiewicz** [comment]
@colby-swandale you can use javascript to do it:

```javascript
window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", (e) => {
  const classList = document.querySelector('html').classList;
  if (e.matches) {
    classList.add('dark');
  } else {
    classList.remove('dark');
  }
});
```

**Comment by natematykiewicz** [comment]
As far as the [theme-color for the top bar](https://github.com/rubyapi/rubyapi/commit/f9980b9fa9900fd32b0ccd4205c5f5f588e3ab6f) goes, you can do a similar thing:

If it's light mode:
```html
<meta name="theme-color" content="#e1175a" />
```

If it's dark mode:
```html
<meta name="theme-color" content="#374151" />
```

If it's system mode:
```html
<meta name="theme-color" content="#e1175a" media="(prefers-color-scheme: light)" />
<meta name="theme-color" content="#374151" media="(prefers-color-scheme: dark)" />
```

**Comment by BytewaveMLP** [comment]
@colby-swandale I'm not sure reverting the commits worked. I still see the theme dropdown on documentation pages, but now it redirects to a URL which 404s. It's not caching, as I've done this with a clean cache.

Personally, I'm a fan of the option to follow the system theme, and giving options is always nice.

**Comment by colby-swandale** [comment]
@natematykiewicz TIL about the `media` attribute on the `theme-color` meta tag, this makes keeping this behaviour super simple. Thanks for pointing that out! 

I've taken a second look and made #1287 that adds a couple new commits to make the `system` theme respect the `prefers-color-scheme` media query. Let me know your thoughts!
