### ISSUE TITLE
Wrong link to GitHub code URL

### ISSUE THREAD

**Issue by natematykiewicz** [rubyapi/rubyapi#1359]
1. Visit
https://rubyapi.org/3.2/o/enumerable#method-i-sort_by
2. Click “View on GitHub”
3. See a 404 at https://github.com/ruby/ruby/blob/v3_2/enum.c#L1472

It should be:
https://github.com/ruby/ruby/blob/v3_2_0/enum.c#L1472

Note the _0 in the URL.

**Comment by colby-swandale** [comment]
oh that's annoying 🫤

IIRC Ruby API uses a convention for Ruby's tag release, maybe instead we should set the git tag in the [ruby.yml](https://github.com/rubyapi/rubyapi/blob/main/config/ruby.yml). What are your thoughts @natematykiewicz ?
