### ISSUE TITLE
RBS Type Signatures toggle appears to fail

### ISSUE THREAD

**Issue by olivierlacan** [rubyapi/rubyapi#1380]
Not seeing an error message in any of the network requests but the request triggered seems to fail: 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/65950/214718786-36282fdb-c7dc-4788-a7ac-72c1a67f8f45.png">

Oddly it also seems to do a full page refresh: 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/65950/214718915-8bcef5ed-f262-494c-a1fd-7fe0d7c33dd5.png">

**Comment by natematykiewicz** [comment]
So I noticed 2 things looking at this just now:


1. It doesn't seems like the button text ever changes. I press the button on the String class, and it does toggle signatures on and off, but the button doesn't change to the word "Disable" ever.

Type Signatures on 
<img width="1333" alt="Screen Shot 2023-01-26 at 11 42 58 PM" src="https://user-images.githubusercontent.com/5104186/215018175-519cb3e2-03fa-42ea-a775-833e51121e9a.png">

Type Signatures off
<img width="1382" alt="Screen Shot 2023-01-26 at 11 42 24 PM" src="https://user-images.githubusercontent.com/5104186/215018162-c926bb2e-58eb-4b49-903d-32b3270c2667.png">


2. I don't think we have OptionParser::Completion type signatures. It's just showing that button if this is Ruby >= 3.0. There's no per-class logic right now (seems like there should be). I see that there's type signatures for [OptionParser](https://rubyapi.org/3.2/o/optionparser) (toggling does change the method definitions), but OptionParser::Completion doesn't seem to work. I know the type signatures are pulled from the [RBS gem](https://github.com/ruby/rbs), but I'm not exactly sure how it all works.

**Comment by olivierlacan** [comment]
Thanks so much @colby-swandale! 😃
