### ISSUE TITLE
Website seems to be down / have cache problems

### ISSUE THREAD

**Issue by louim** [rubyapi/rubyapi#1866]
Hey! When I try to click on any page or use the search function, I get a page similar to this:
![image](https://github.com/rubyapi/rubyapi/assets/923718/ddebafa9-4021-44ec-8595-0591500410ba)

```
Error 503 first byte timeout

first byte timeout

Error 54113

Details: cache-yul12821-YUL 1707445815 3182240675


Varnish cache server
```

**Comment by colby-swandale** [comment]
I'm currently investigating

**Comment by louim** [comment]
@colby-swandale Thanks! It seems to be back up for me. I'll leave you to close the issue if the problem is resolved.
