### ISSUE TITLE
Allocations are too dam high

### ISSUE THREAD

**Issue by colby-swandale** [rubyapi/rubyapi#191]
Not sure why we're allocating 10s of thousands of objects in the object show page.

https://oss.skylight.io/app/applications/k1noEyWLdXuJ/1569499140/45m/endpoints/ObjectsController%23show?mode=memory&responseType=html

**Comment by natematykiewicz** [comment]
Skylight seems fine with the amount of allocations these days. So, I think we're good to close this one!

**Comment by colby-swandale** [comment]
I agree! Thank you again for looking into this! You should totally write up about a blog post about reducing the allocations down by ~50%!
