### ISSUE TITLE
Changing theme doesn't work

### ISSUE THREAD

**Issue by leonovk** [rubyapi/rubyapi#1913]
When I try to change themes, the site gives a 422 error

**Comment by natematykiewicz** [comment]
<img width="392" alt="Screenshot 2024-03-26 at 3 34 08 PM" src="https://github.com/rubyapi/rubyapi/assets/5104186/d8f09625-918f-4300-931e-9c2762bcdfc8">

**Comment by leonovk** [comment]
It’s interesting, I launched the project locally according to the instructions and do not observe such a problem.

**Comment by leonovk** [comment]
Also when i press the "Enable Type Signatures" button the exact same error appears

**Comment by colby-swandale** [comment]
Apologies for the long delay in replying 🙇🏻 This was breaking due to some CSRF exceptions, i've pushed a fix in https://github.com/rubyapi/rubyapi/commit/11681910f1a0b2633f32db7347ebb71f347bfba6. Thank you for helping improve Ruby API!
