### ISSUE TITLE
Searching for common initializers leads to random places (e.g. Array.new)

### ISSUE THREAD

**Issue by tadman** [rubyapi/rubyapi#192]
Building on [Issue #101]: Perplexingly a [search for "Array.new"](https://rubyapi.org/2.6/o/s?q=Array.new) goes in completely unexpected directions.

![Screen Shot 2019-09-26 at 3 34 46 PM](https://user-images.githubusercontent.com/6184/65719216-47161080-e073-11e9-8e6d-fe22c273c82b.png)

The documentation is sometimes inconsistent about how it documents things, like is it `X.new` or `X#initialize`. In most cases `X#initialize` should have a default stub as `X.new` unless `X.new` is explicitly defined, something that's the case in a few libraries.

**Comment by colby-swandale** [comment]
:wave: I've added a couple of changes that should help resolve this problem. Searching for `Array.new` and will show `Array::new` as the first result, but I'm not confident this problem is fully solved.

**Comment by colby-swandale** [comment]
Marking this as resolved.
