### ISSUE TITLE
Class names not being prioritized in search

### ISSUE THREAD

**Issue by tjwallace** [rubyapi/rubyapi#193]
When I search for `Set` I'd expect to find `Set` (class) in the first few results but it is not there:
![image](https://user-images.githubusercontent.com/91084/65621420-90356a00-df78-11e9-8d8f-13d3d3d43067.png)

When I search for `Array` I get better results:
![image](https://user-images.githubusercontent.com/91084/65621389-8449a800-df78-11e9-9a1e-a6b43cbce3fb.png)

_Originally posted by @tjwallace in https://github.com/rubyapi/rubyapi/issues/145#issuecomment-535108565_

**Comment by colby-swandale** [comment]
👋 Sorry for the delay in responding back. I've tweaked the autocomplete/search results so that classes are better scored in the results.

`Set` should now be appearing at the top.

**Comment by tjwallace** [comment]
Works great now, thanks!
