### ISSUE TITLE
503 and 504 errors for rubiapi.org

### ISSUE THREAD

**Issue by andyw8** [rubyapi/rubyapi#2012]
Hi, I've been having loading problems for the last couple of days. I don't see any issue listed on the [status page](https://rubyapi-org.statuspage.io/).

e.g. https://rubyapi.org/3.4/o/s?q=gsub is currently returning:

```
Error 503 first byte timeout
first byte timeout

Error 54113
Details: cache-lga21975-LGA 1718803716 2750839454

Varnish cache server
```

for other requests I'm getting "504 Gateway Time-out".

**Comment by colby-swandale** [comment]
Apologies for the interruption, i was making some tweaks behind the scenes and the OpenSearch cluster managed to get caught in the cross fire, I've patched things up again and should be good now.

**Comment by colby-swandale** [comment]
I pulled the trigger a bit too quickly and see the site is still not working correctly. Looking into it now.

**Comment by colby-swandale** [comment]
Okay now everything should be good now 🙌🏻

**Comment by andyw8** [comment]
:wave: Still seeing failures for rhttps://rubyapi.org/3.4/o/s?q=gsub
