### ISSUE TITLE
Chrome thinks status page is phishing

### ISSUE THREAD

**Issue by andyw8** [rubyapi/rubyapi#2013]
Not sure if there is a way to prevent this:

<img width="665" alt="Screenshot 2024-06-19 at 9 33 56 AM" src="https://github.com/rubyapi/rubyapi/assets/13400/bf6fa0f7-cd4a-44fa-8b20-87f248a86a71">

(for https://rubyapi-org.statuspage.io/)

**Comment by colby-swandale** [comment]
I've discontinued using statuspage (explained in #2020) and removed all links to the service, so i think this is no longer an issue. But feel free to let me know otherwise.
