### ISSUE TITLE
Everything, excepts the homepage, returns a 404

### ISSUE THREAD

**Issue by Uaitt** [rubyapi/rubyapi#2015]
Today I have noticed that almost the whole website, except the homepage, seems to return 404.

https://github.com/rubyapi/rubyapi/assets/97030518/f67503fc-f759-40b7-a4e0-10af2806e225

**Comment by devsheva** [comment]
same here

**Comment by devsheva** [comment]
now is back i guess

**Comment by colby-swandale** [comment]
Apologies for not responding to this ticket. I did resolve the outage and have also recently added Datadog monitoring to alert me directly of any future issues.
