### ISSUE TITLE
Uptime monitoring?

### ISSUE THREAD

**Issue by andyw8** [rubyapi/rubyapi#2020]
To help detect issues such as https://github.com/rubyapi/rubyapi/issues/2015 and https://github.com/rubyapi/rubyapi/issues/2012, perhaps some basic uptime monitoring could be considered?

**Comment by andyw8** [comment]
(it might just involve some extra checks for https://rubyapi-org.statuspage.io)

**Comment by colby-swandale** [comment]
Thanks for bringing this to my attention and I apologies for the long delay in responding to this issue. I've recently added application monitoring via Datadog that will now alert me directly when the application encounters any errors.

Regarding the status page, I added the service last year with some plans to put it into the care of the rubygems.org on-call team, which I'm a part of, but it never came to fruition and I have no plans to use it going forward. I've disconnected the service and have removed the link entirely from the site.
