### ISSUE TITLE
500's not caught by uptime monitoring?

### ISSUE THREAD

**Issue by gerrywastaken** [rubyapi/rubyapi#2079]
Hey folks, so I've noticed [the site](https://rubyapi.org/o/stringscanner) seems to be returning 500s the last two days (possibly longer but I didn't check), however the uptime monitoring is returning all green.

![Screenshot from 2024-08-15 15-53-19](https://github.com/user-attachments/assets/20b2edf3-9765-45ec-ad9a-7df6ea7739d0)
![Screenshot from 2024-08-15 15-57-18](https://github.com/user-attachments/assets/e3867612-d2f2-4dd7-9649-605cd1351cc8)

**Comment by colby-swandale** [comment]
Thanks for bringing this to my attention and I apologies for the long delay in getting this issue resolved. I restored the service laster night, and I've added application monitoring via Datadog that will now alert me directly when the application encounters any errors.

**Comment by gerrywastaken** [comment]
Awesome, cheers Colby! Hope you are doing well! :) The changes make sense and I hope the monitoring only notifies you when it is convenient time. Don't make yourself oncall :) No apologies necessary and thank you for supporting the service and for creating a far more usable version of the docs. :heart:
