### ISSUE TITLE
Can't select search results

### ISSUE THREAD

**Issue by fidalgo** [rubyapi/rubyapi#242]
First of all thanks for this project :heart_eyes: 

When searching like `include` I cannot select a result from the search box.

**Comment by colby-swandale** [comment]
:wave: Sorry to hear you're having issues on rubyapi. 

Can you just describe the basic environment (ie: Browser Agent, Operating System) you're using that i can use to test & try to resolve this problem?

**Comment by fidalgo** [comment]
Sorry, I should add it in the first comment:

Firefox 71:
```
Operating system: Fedora
Javascript enabled: Yes
Cookies enabled: Yes
Flash version: Not installed
Java version: Not installed
Websockets supported: Yes
WebGL supported:Yes
Language: en-US
Browser size: 2552 x 1307
Screen size: 2560 x 1440 (Retina)
Color depth: 24 bit

full user agent string is:
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
```
Chromium:
```
Operating system: Linux x86_64
Javascript enabled: Yes
Cookies enabled: Yes
Flash version: Not installed
Java version: Not installed
Websockets supported: Yes
WebGL supported: Yes
Language: en-GB
Browser size: 1991 x 1309
Screen size: 2560 x 1440 (Retina)
Color depth: 24 bit

full user agent string is:
Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```

**Comment by tadman** [comment]
Same problem here in both Safari and Chrome (macOS 10.15)

![Screen Recording 2019-12-18 at 10 06 38 PM](https://user-images.githubusercontent.com/6184/71141685-fb42b580-21e2-11ea-9034-e820e0aaf4ed.gif)

**Comment by colby-swandale** [comment]
Thank you for letting know about the issue! I wasn't seeing this problem because of a timing issue that wasn't showing up on my laptop.

I've been using a really bad & hacky bit of Javascript to hide the autocomplete results when the user clicks on a link but also have the browser visit that link as well.

I've updated the code that should remove this timing issue and allow you click on links again.

Let me know if this has solved your problem!

**Comment by tadman** [comment]
Works now, nice!

**Comment by fidalgo** [comment]
Problem solved here, too! :tada:  Thanks a lot!
