### ISSUE TITLE
NameError (uninitialized constant Shellwords)

### ISSUE THREAD

**Issue by khiav223577** [rubyapi/rubyapi#287]
I got this error when trying to run the below example:
![image](https://user-images.githubusercontent.com/4011729/74356585-9037e880-4df9-11ea-8c9a-d22497b1fc1c.png)

**Comment by bronzdoc** [comment]
@khiav223577 thanks for the report!

I'm not able to reproduce it, I'm definitely not getting the output I expected but not an error

![Screen Shot 2020-02-14 at 10 51 30 AM](https://user-images.githubusercontent.com/4595174/74550991-fdda3680-4f17-11ea-9735-cd185c190efa.png)

**Comment by colby-swandale** [comment]
@bronzdoc ah this is my fault. The docker server running the code examples died last night and i've done a really bad/non existent job handling errors.

The executable docs are working again now, so we should be able to replicate this problem

**Comment by bronzdoc** [comment]
Hi @khiav223577 the problem was in the service that runs the code snippets. I submitted a PR with a fix in https://github.com/rubyapi/code-runtime/pull/2
