### ISSUE TITLE
`Parent` and `Included Modules` in side menu

### ISSUE THREAD

**Issue by AlexWayfer** [rubyapi/rubyapi#288]
Hello!

Please, add `Parent` and `Included Modules` sections in side menu alongside methods.

Reference: https://ruby-doc.org/core-2.7.0/Array.html

---

![image](https://user-images.githubusercontent.com/6510020/74429438-0412d900-4e6c-11ea-80dc-1896ec839741.png)

---

![image](https://user-images.githubusercontent.com/6510020/74429479-142ab880-4e6c-11ea-9f5a-8106806bbe87.png)

**Comment by ioquatix** [comment]
If the parent is Object, is there any point to list it?

**Comment by AlexWayfer** [comment]
> If the parent is Object, is there any point to list it?

I think, yes. It can be `Object`, `BasicObject`. Why we should display `BasicObject`, but not `Object`? That's strange.

Also, there is no parent for modules like `Kernel` or `Enumerable`:

![image](https://user-images.githubusercontent.com/6510020/74430398-d2027680-4e6d-11ea-86c2-3ccee2c46c88.png)

But! For `BasicObject` there is empty section:

![image](https://user-images.githubusercontent.com/6510020/74430449-e9416400-4e6d-11ea-98f7-12786bb719d1.png)

That's quite interesting, logical, clear.

**Comment by ioquatix** [comment]
I wonder if we can experiment with a slightly more elaborate syntax... e.g. the title could be

```
class String < Object
```

or

```
module Enumerable
```

we can use CSS to draw attention to the main name, but the rest of the information is still present.

**Comment by AlexWayfer** [comment]
Probably. We already have `Class` in the right top corner.

And also we can write below something like:

```ruby
include Enumerable
```

(clickable, as parent class)

**Comment by colby-swandale** [comment]
I agree with this :100:. I think the sidebar is probably the best place but i am defiantly open to alternatives as well.
