### ISSUE TITLE
Z-index issue between search field and version drop-down

### ISSUE THREAD

**Issue by AlexWayfer** [rubyapi/rubyapi#289]
Hello!

There is a small issue with overlapping:

![image](https://user-images.githubusercontent.com/6510020/74429688-77b4e600-4e6c-11ea-969a-5ee3946d94f4.png)

(on the main page)

**Comment by AlexWayfer** [comment]
Thank you!

**Comment by bronzdoc** [comment]
Thank you for the issue report @AlexWayfer !
