### ISSUE TITLE
Theme selection

### ISSUE THREAD

**Issue by AlexWayfer** [rubyapi/rubyapi#290]
Hello!

It'd be nice to have site UI theme selection somewhere, for example, between light and dark.

**Comment by colby-swandale** [comment]
The day/night themes are currently being set by the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media selector. I'm not sure if there is a way to toggle this with JS or if there's a better way we can handle day/night colors with Tailwind CSS. Any help is welcome on this.

**Comment by JuanitoFatas** [comment]
I will look into this.

**Comment by ioquatix** [comment]
I’m okay with automatic theme selection. For me it just works perfectly.

**Comment by natematykiewicz** [comment]
@colby-swandale you can close this now, since #323 was merged, right?

**Comment by natematykiewicz** [comment]
So now that #323 got merged, any chance we could get automatic theme selection added back in? Previously, the site followed the OS setting. Now it's locked to whatever the OS was configured to the first time you visited the site.

I feel like a 3-state option of Light, Dark, Auto (if supported) would be best.

**Comment by colby-swandale** [comment]
Oh you're right @natematykiewicz, thanks for raising that. There should be a third option to use the OS setting. 
 
My immediate thought to resolve this - is to make the button a popover, like the Github and versions popovers and present all 3 options there. Does that sound good to you?

**Comment by AlexWayfer** [comment]
I think, we should have OS-depending theme by default, and save manual change. I think, there is no need for the third option in this case. Scenario:

* You visit RubyAPI with light OS theme — you get light site.
* Then you visit with dark OS theme — you get dark site.
* Then you visit with light OS theme and you get light site again, and so on.
* But, if you once toggle the switcher manually, for example, from light to dark — you now get dark theme all the time, independent from OS theme, it's your choice.

Yes, there may be a wish to reset your choice and come back to auto-mode, but I'm not sure someone will wish so. I suggest to wait for such feedback. 

I think, the most users have single OS theme, light or dark, and switch it very rare. I know about macOS feature with auto-switch, but I think it's rare used too. And if someone uses it — I guess they will not toggle site theme manually.

**Comment by natematykiewicz** [comment]
@AlexWayfer I don't like that at all. A lot of sites offer the 3-state option. Your suggestion means that I could be curious what this new icon does, click it, realize I don't like that, and have no way back because I "made a choice".

Not having a way back into "automatic" mode is a pretty bad UX for people whose browsers support "automatic" (whether they meant to manually change themes or not).

@colby-swandale I was thinking exactly that!

**Comment by AlexWayfer** [comment]
> A lot of sites offer the 3-state option

Can you please provide some examples? My examples [here](https://github.com/rubyapi/rubyapi/pull/296#issuecomment-588150370) from Twitter, Twitch, YouTube have 2 states (Twitter has 3, but they're like "dark" and "black").

> Your suggestion means that I could be curious what this new icon does, click it, realize I don't like that, and have no way back because I "made a choice".

Yes, but… what do you not like? For example, you're on light theme, you're curious and switch it to dark, you realize that you don't like dark theme and switch back to light. Now you have light theme and you don't like the dark one — sounds correct.

**Comment by natematykiewicz** [comment]
> Can you please provide some examples? My examples [here](https://github.com/rubyapi/rubyapi/pull/296#issuecomment-588150370) from Twitter, Twitch, YouTube have 2 states (Twitter has 3, but they're like "dark" and "black").

I can't find any in web apps, but lots of native apps on iOS/mac do this.

Slack's mac app.
<img width="810" alt="Screen Shot 2020-07-20 at 9 15 52 AM" src="https://user-images.githubusercontent.com/5104186/87947947-abbeb380-ca69-11ea-94bb-7a679f625d76.png">

Twitter's iOS app. (The first toggle automatically changes, if the second one is on.)
![IMG_4C252A0F644D-1](https://user-images.githubusercontent.com/5104186/87948243-1112a480-ca6a-11ea-9df1-41ef30df0dcf.jpeg)

GitHub mobile app.
![IMG_B3A8774E3EA0-1](https://user-images.githubusercontent.com/5104186/87948857-dc531d00-ca6a-11ea-8217-108bd18cc43f.jpeg)

Facebook Messenger app.
![IMG_1C10E6471298-1](https://user-images.githubusercontent.com/5104186/87948634-95fdbe00-ca6a-11ea-95c0-673660522332.jpeg)


> Yes, but… what do you not like?

I don't like a website taking away a core OS feature for no reason. It feels like you're punishing the user, and it can leave them feeling regretful that they ever touched the options when it "just worked"™️ before.

Full disclosure: I was fine when the site didn't have an option to manually change it. But now that it's got an option, I don't like that the option to go back to automatic is gone.

**Comment by colby-swandale** [comment]
We've had a toggle to switch between the light/dark themes for a while now, so I'm going to mark this issue as complete!

**Comment by colby-swandale** [comment]
If we still feel strongly for have a system-default option, feel free to open a new issue that we can track. Thanks.
