### ISSUE TITLE
Listing of Methods Visible on Mobile

### ISSUE THREAD

**Issue by pyrmont** [rubyapi/rubyapi#291]
I'd like to request that Ruby API's web interface expose a listing of methods for a particular class.

I realise that to some extent this is an aesthetic decision and reasonable people may disagree. My argument would be that users may sometimes have an inkling of what they're looking for but nevertheless find it useful to quickly see the list of available methods. At the moment, the options are to search (which can be frustrating if you don't pick the correct wording) or to scan the documentation for a class (which can be time-consuming in big classes).

On mobile, it would most likely make sense to have this listing hidden behind some kind of menu.

**Comment by AlexWayfer** [comment]
Sorry, what do you mean? Do you have examples or mock-ups? I understand it like existing sidebar (it contains a lists of methods for a particular class).

**Comment by pyrmont** [comment]
@AlexWayfer It's been a while since I filed the report so I don't remember the complete context now but the issue for me is specifically about mobile. I'm sorry for not being clearer about that. On desktop, there _is_ a nice sidebar. The problem is that, on mobile, the sidebar is hidden and there is no way to access it (at least as far as I can tell).

Basically my request is for some way to access this sidebar on mobile. There are other ways to achieve this I'm sure but the two most obvious ones that come to mind are: (1) a tappable menu control (similar to the way the Ruby version can be tapped currently) or (2) the sidebar being moved below the main content 'column' on mobile.

**Comment by AlexWayfer** [comment]
@pyrmont OK, I got it and confirm that I don't see the sidebar on mobile. Thank you!

**Comment by AlexWayfer** [comment]
I personally don't like using Tailwind CSS, it's not better than `style` attribute with CSS in HTML. But I'll think how to implement it.

**Comment by AlexWayfer** [comment]
Implemented in #389 . :tada:
