### ISSUE TITLE
Misses methods that are extended

### ISSUE THREAD

**Issue by connorshea** [rubyapi/rubyapi#346]
This is a weird edge case, but I figured I'd point it out.

`Coverage` has a method called `line_stub`. Most methods on Coverage are written in C, but `line_stub` is [written in Ruby](https://github.com/ruby/ruby/blob/v2_7_0/ext/coverage/lib/coverage.rb#L4).

[Ruby-Doc catches this method](https://ruby-doc.org/stdlib-2.7.0/libdoc/coverage/rdoc/Coverage.html#method-c-line_stub), but [Ruby API does not](https://rubyapi.org/2.7/o/coverage).

**Comment by connorshea** [comment]
I guess it's not "extended", idk what to call it 🤔

**Comment by natematykiewicz** [comment]
```ruby
@documentation.each do |doc|
  next if skip_namespace? doc.full_name
  methods = []

  doc.method_list.each do |method_doc|
    puts method_doc if doc.full_name == 'Coverage' # Added this for debugging
    next if methods.find { |m| m[:name] == method_doc.name }
```

> RDoc::AnyMethod: Coverage::start
> RDoc::AnyMethod: Coverage::result
> RDoc::AnyMethod: Coverage::peek_result
> RDoc::AnyMethod: Coverage::running?

Weird `line_stub` isn't printed.

**Comment by colby-swandale** [comment]
I'm getting the sense that the importer is not correctly finding/generating some methods/objects. There's also now #460 

I'll spent some time to see if i can figure this out but any imput/ideas are welcome.

**Comment by colby-swandale** [comment]
Actually, i bet it will be because of the line:

    next if methods.find { |m| m[:name] == method_doc.name }

**Comment by AlexWayfer** [comment]
> There's also now #460

Is it correct reference? I don't understand its meaning.

**Comment by AlexWayfer** [comment]
> Actually, i bet it will be because of the line:
> 
> ```
> next if methods.find { |m| m[:name] == method_doc.name }
> ```

Why do you think that this is because of the line which places after @natematykiewicz's debug which doesn't print this method?

I guess the generator even doesn't know about [this ext file](https://github.com/ruby/ruby/blob/v2_7_0/ext/coverage/lib/coverage.rb#L4). Maybe we should call something like `require 'coverage'` before generator runs, maybe not only with `coverage`, but I'm not sure.

By the way I confirm that @natematykiewicz's debug still doesn't print this method, even after all of changes there.

**Comment by colby-swandale** [comment]
Yea, the issue seems to be that RDoc is not generating the documentation in the first place. I'm not sure what rubydoc.org is doing to find this method because [docs.ruby-lang.org is also missing this method](https://docs.ruby-lang.org/en/2.7.0/Coverage.html).

**Comment by AlexWayfer** [comment]
> I'm not sure what rubydoc.org is doing to find this method because [docs.ruby-lang.org is also missing this method](https://docs.ruby-lang.org/en/2.7.0/Coverage.html).

1. I guess, you meant ruby-doc.org, not rubydoc.org.
2. I've sent an email to them with the question from this issue, @colby-swandale is in CC.

**Comment by natematykiewicz** [comment]
Wait, there's a ruby-doc.org and a rubydoc.org? 🤦 

Yeah, I think the problem has to do with RDoc. Perhaps it's worth looking into submitting an RDoc PR?

**Comment by Neurogami** [comment]
It's complicated.  Getting proper Rdoc for the std-lib on ruby-doc.org has a been a every-evolving challenge for me.  So over the years I've crafted assorted scripts to manage correct doc'ing of libs.  You have to look a carefully at what files constitute a library, where do they live, and how do you tell rdoc to include them.

(Yes, I run ruby-doc.org)

**Comment by colby-swandale** [comment]
I can see that `Coverage.line_stub` now correctly shows up on Ruby API https://rubyapi.org/3.0/o/coverage#method-c-line_stub. I'm going to mark this issue as resolved, but please let me know if there are other instances of this problem.
