### ISSUE TITLE
"See also" links are incorrect

### ISSUE THREAD

**Issue by natematykiewicz** [rubyapi/rubyapi#361]
I was watching @ioquatix's Async::HTTP::Cache video and noticed weird errors in the benchmarker, so I paused the video.

![Screen Shot 2020-04-04 at 10 54 13 AM](https://user-images.githubusercontent.com/5104186/78455249-bd1eb400-7662-11ea-96f4-c96facf70310.png)

On https://rubyapi.org/2.7/o/string#method-i-concat

```html
<p>See also <a href="String.html#method-i-3C-3C"><code>String#&lt;&lt;</code></a>, which takes a single argument.</p>
```

Seems like that url should either simply be `#method-i-3C-3C` or `/2.7/o/string.html#method-i-3C-3C`. But this `String.html` path is wrong.

Interestingly, my browser makes a sensible URL out of it. `https://rubyapi.org/2.7/o/String.html#method-i-3C-3C`. And since Rails interprets the `.html` as the format of HTML (which is the default), and Elasticsearch finds `String` just fine (case insensitive search), the link actually works fine.

But still, the URL there is not consistent with the rest of the app. Maybe we don’t care, but I believe this will cause page caching to store multiple copies of the page in memory, unless Async::HTTP::Cache is doing some sort of URL normalization on cache lookups.

**Comment by natematykiewicz** [comment]
Looking into this, this is simply the `RubyMethod`'s `description` property.

# View Code:
```slim
div class="ruby-documentation py-1"
  - if m.description.empty?
    div
      | No documentation available
  - else
    == m.description
```

# m.description:

```html
<p>Concatenates the given object(s) to <em>str</em>. If an object is an <a href="Integer.html"><code>Integer</code></a>, it is considered a codepoint and converted to a character before concatenation.</p>

<p><code>concat</code> can take multiple arguments, and all the arguments are concatenated in order.</p>

<div class="ruby" data-controller="code-example" data-target="code-example.block" data-code-example-version="2.7"><div class="w-full px-3 py-2 bg-code-header dark:bg-gray-700 items-center flex justify-between font-mono rounded-t"><h4 class="text-gray-300 text-sm">Example</h4><div><button class="px-2" data-action="click->code-example#run"><span class="text-gray-300 fill-current hover:text-gray-500" data-target="code-example.run"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="play" class="svg-inline--fa fa-play fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z" data-darkreader-inline-fill="" style="--darkreader-inline-fill: currentColor;"></path></svg><!-- <i class="fas fa-play"></i> --></span></button><button tilte="Copy to clipboard" class="pl-2" data-action="click->code-example#copy" aria-label="Copy to clipboard"><span data-target="code-example.copy" class="text-gray-300 fill-current hover:text-gray-500"><svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="copy" class="svg-inline--fa fa-copy fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M433.941 65.941l-51.882-51.882A48 48 0 0 0 348.118 0H176c-26.51 0-48 21.49-48 48v48H48c-26.51 0-48 21.49-48 48v320c0 26.51 21.49 48 48 48h224c26.51 0 48-21.49 48-48v-48h80c26.51 0 48-21.49 48-48V99.882a48 48 0 0 0-14.059-33.941zM266 464H54a6 6 0 0 1-6-6V150a6 6 0 0 1 6-6h74v224c0 26.51 21.49 48 48 48h96v42a6 6 0 0 1-6 6zm128-96H182a6 6 0 0 1-6-6V54a6 6 0 0 1 6-6h106v88c0 13.255 10.745 24 24 24h88v202a6 6 0 0 1-6 6zm6-256h-64V48h9.632c1.591 0 3.117.632 4.243 1.757l48.368 48.368a6 6 0 0 1 1.757 4.243V112z" data-darkreader-inline-fill="" style="--darkreader-inline-fill: currentColor;"></path></svg><!-- <i class="far fa-copy"></i> --></span></button></div></div></div><pre class="ruby"><span class="ruby-identifier">a</span> = <span class="ruby-string">"hello "</span>
<span class="ruby-identifier">a</span>.<span class="ruby-identifier">concat</span>(<span class="ruby-string">"world"</span>, <span class="ruby-value">33</span>)      <span class="ruby-comment">#=&gt; "hello world!"</span>
<span class="ruby-identifier">a</span>                          <span class="ruby-comment">#=&gt; "hello world!"</span>

<span class="ruby-identifier">b</span> = <span class="ruby-string">"sn"</span>
<span class="ruby-identifier">b</span>.<span class="ruby-identifier">concat</span>(<span class="ruby-string">"_"</span>, <span class="ruby-identifier">b</span>, <span class="ruby-string">"_"</span>, <span class="ruby-identifier">b</span>)   <span class="ruby-comment">#=&gt; "sn_sn_sn"</span>
</pre>

<p>See also <a href="String.html#method-i-3C-3C"><code>String#&lt;&lt;</code></a>, which takes a single argument.</p>
```

So, this one would need to be addressed in the importer.

**Comment by natematykiewicz** [comment]
Oh, and like 30 sends later in the video, he actually points out the errors. Haha.

@ioquatix in the video you were pointing out that the contents of the `<code></code>` should be escaped, right? Do you believe that's something that this project should do, or RubyDoc?

**Comment by ioquatix** [comment]
Is `m.description` the field which contains that incorrect HTML?

**Comment by natematykiewicz** [comment]
Yup. I posted the a ‘m.description’ example a few comments above.

**Comment by ioquatix** [comment]
I guess we should fix rdoc:

https://github.com/ruby/rdoc/issues/761

**Comment by natematykiewicz** [comment]
@ioquatix, what are your thoughts on updating this URL in the importer, to be consistent with the rest of the app? I believe they’ll result in a cache miss in Async::HTTP::Cache at the moment, using more memory than necessary.

**Comment by ioquatix** [comment]
Fixing the URL makes sense. It could make the cache a bit more efficient.

**Comment by natematykiewicz** [comment]
An alternative idea is add another route to the router that catches a “String.html” and just redirects to the normal “string” path. That would be a lot simpler. But I don’t know if that helps anything. My thought is that if the RDoc-style URLs were always a redirect, it would take up less space in the cache. But of course it’d be slightly less efficient for the browser.

Thoughts?

**Comment by ioquatix** [comment]
There are a couple of options:

1. Rewrite URLs - can this be done at the RDoc layer or do we have to rewrite the HTML? You could use Trenni::Parser to pull out `<a>` tags quickly, the parser is written in C.
2. Add redirects. Adds a little bit of latency but if we missed rewriting any links, it would also be more reliable.

The falcon cache doesn't currently support caching redirects, but eventually it will. Redirects should be pretty quick. You could also consider adding https://instant.page/

**Comment by natematykiewicz** [comment]
Unfortunately, I doubt we'll be able to solve this problem with Trenni::Parser at the moment. The screenshot from your live stream is a `Trenni::ParserError` because it can't always parse the `<a>`, given the current invalid HTML.

Perhaps there's a way to use `Trenni::Parser` to find the appropriate tags, and then fix the RDoc problem _**and**_ the URLs all at the same time? Not sure.

**Comment by ioquatix** [comment]
If you make a PR on rdoc I can review and merge it today

**Comment by natematykiewicz** [comment]
I'll see what I can do

**Comment by natematykiewicz** [comment]
@ioquatix https://github.com/ruby/rdoc/pull/762 the CI passes

**Comment by ioquatix** [comment]
Awesome, merged. There is no guarantee a release is quick so should we just point rdoc at the master branch before generating the HTML?

**Comment by natematykiewicz** [comment]
I guess that one is up to @colby-swandale. Is there any harm in just adding RDoc to the Gemfile and pointing it to master, and committing that?

Later on, we'd theoretically want to require `>= 6.2.2`.

**Comment by ioquatix** [comment]
If you can make a pr I will merge if pointing at master should be fine

**Comment by natematykiewicz** [comment]
I've made good progress on this, but there's more RDoc problems. https://github.com/ruby/rdoc/issues/763

**Comment by colby-swandale** [comment]
Unless the changes between `master` and the the most recent release are very minor, I would strongly prefer waiting for the rdoc team to release a new patch version rather then pulling down `master`. I just don't want to be needing to handle breaking changes or having unreleased features.

**Comment by natematykiewicz** [comment]
Is see. You mean the other things between the current release and my bug fix?

https://github.com/ruby/rdoc/commit/b120d087f60ca093a45b7f982b3660acc109325e

My intention was to get that specific commit, but your concern makes a lot of sense.

I could remove rdoc from the Gemfile and we’d still have a massive improvement for Ruby API, documentation. RDoc still has other problems in the documentation, but I made the cleaner very optimistic about cleaning. If it can’t parse the description, it uses what it’s cleaned so far using the `gsub`s. That gives us the most possible cleaning.

I’d recommend that you release this fix using the current released version instead of waiting for the next RDoc release, which could be months from now for all I know. There’s lots of brokenness that this fixes. For example, most of the namespaced classes are broken on the search results pages, because they use relative urls that expect to be able to navigate up the tree to a different class from whatever class the method is on. “../../Net/FTP.html” is an example of what I’m talking about.

Either way, you’ll want to reimport all Ruby versions into Ruby API every time there’s a new RDoc release, until all of these RDoc bugs get fixed.

**Comment by natematykiewicz** [comment]
Actually. I think it would make sense to keep `gem "rdoc"` in the Gemfile, so that Dependabot can tell you when a new version comes out, and also what the difference is.

**Comment by natematykiewicz** [comment]
@colby-swandale I've pushed another commit.

https://github.com/rubyapi/rubyapi/pull/369/commits/1ceaaa50ef2251574cd50e632b994659797cdcdf

Let me know if you have anymore feedback!

**Comment by natematykiewicz** [comment]
Here's an example of a problem that this fixes:

https://rubyapi.org/2.7/o/PP.html

Click the "PPMethods" link on the left in "Included Modules". You get a 404. The correct URL is https://rubyapi.org/2.7/o/pp/ppmethods
