### ISSUE TITLE
Thanks!! ⭐️

### ISSUE THREAD

**Issue by sandstrom** [rubyapi/rubyapi#425]
Just wanted to say thank you for an awesome project! @colby-swandale 

The standard Ruby documentation feels a bit dated. Your's is a great improvement!

![applause2](https://user-images.githubusercontent.com/122287/82300733-89e87800-99b7-11ea-990f-41bd61c36cce.gif)

**Comment by colby-swandale** [comment]
Thank you so much for your kind words 👏 I'm super happy you like the project!
