### ISSUE TITLE
[docs] Setting up with Docker

### ISSUE THREAD

**Issue by janklimo** [rubyapi/rubyapi#484]
This is possibly a dumb question but it might help improve the docs to onboard contributors not experienced with Docker.

Having run the recommended command:

```
docker-compose up -d
Creating network "rubyapi_default" with the default driver
Creating rubyapi_elasticsearch_1 ... done
Creating rubyapi_kibana_1        ... done
```

It still appears the app can't connect to ES:

```
./bin/rake import:ruby:all
W, [2020-07-22T18:21:40.626495 #90025]  WARN -- Skylight: [SKYLIGHT] [4.3.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Found previously extracted download for 2.7.1, skipping
\ Importing Ruby 2.7.1 documentationrake aborted!
Faraday::ConnectionFailed: Couldn't connect to server
/Users/jan/OSS/rubyapi/lib/rubyapi_rdoc_generator.rb:103:in `reset_indexes!'
/Users/jan/OSS/rubyapi/lib/rubyapi_rdoc_generator.rb:29:in `generate'
/Users/jan/OSS/rubyapi/lib/ruby_documentation_importer.rb:36:in `import'
/Users/jan/OSS/rubyapi/lib/ruby_documentation_importer.rb:11:in `import'
/Users/jan/OSS/rubyapi/lib/tasks/import.rake:27:in `block (4 levels) in <main>'
/Users/jan/OSS/rubyapi/lib/tasks/import.rake:25:in `each'
/Users/jan/OSS/rubyapi/lib/tasks/import.rake:25:in `block (3 levels) in <main>'
```

I can run the server and run localhost but same thing happens when I try to search. Is anything missing in the getting started steps?

**Comment by colby-swandale** [comment]
It looks like you're using MacOS, so running docker compose up should be enough . Are you running [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) on your local machine, or are you running docker on a remote host somewhere else?

**Comment by janklimo** [comment]
Thank you @colby-swandale strangely, it's working fine today and I don't think I changed anything so hard to say how to update the docs. I suppose it's all good 👍
