### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by AlexWayfer** [rubyapi/rubyapi#536]
https://ruby-doc.org/core-2.7.1/File.html

![image](https://user-images.githubusercontent.com/6510020/92627926-bb71b000-f2d4-11ea-8811-99c16c3ec472.png)

https://rubyapi.org/2.7/o/file

![image](https://user-images.githubusercontent.com/6510020/92627973-cdebe980-f2d4-11ea-8b75-6444158fddc5.png)

**Comment by colby-swandale** [comment]
See #501

**Comment by AlexWayfer** [comment]
> See #501

Oh, sorry, I looked for it in issues, not PRs. Closing as a duplicate.

**Comment by colby-swandale** [comment]
I'm happy to keep this issue open to track #501

**Comment by AlexWayfer** [comment]
> I'm happy to keep this issue open to track #501

OK, then you can mark #501 as resolving this issue.

**Comment by AlexWayfer** [comment]
I see #501 was merged and also I see constant on prod. I guess, we can close this issue now? Thank you very much.
