### ISSUE TITLE
Add an Open Search Description for quick-searching from Chrome's Omnibox

### ISSUE THREAD

**Issue by AaronC81** [rubyapi/rubyapi#569]
First of all, thanks for your work on this project! It's a fantastic resource, much slicker than the official Ruby docs, and I've been using it loads.

It would be really cool if the site had an Open Search Description file (described [here](https://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site)). Then, you could jump straight into a search on the docs by typing enough of rubyapi.org for Chrome to suggest it, and then hitting Tab to type a search query right in Chrome's URL bar.

I'm happy to take a look at adding this if you think it's a good idea :)

**Comment by natematykiewicz** [comment]
I know @colby-swandale added this:
https://github.com/rubyapi/rubyapi/blob/master/app/views/home/index.html.slim#L4-L14

I'm honestly not sure what it does. Sounds similar, though.

**Comment by AlexWayfer** [comment]
> Sounds similar, though.

As I understand, they're different things.

https://github.com/rubyapi/rubyapi/commit/a8e284eb7b832f272d519d7494e35a8b59b8d57e

This is for SEO (like everything from schema.org, as I know).

And Open Search is for describing search engine for a browser: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by colby-swandale** [comment]
@natematykiewicz json blob in your screenshot is the [opengraph for google.com search](https://developers.google.com/search/docs/data-types/sitelinks-searchbox), which it may decide, not-decide to show a search bar in the google search results.

@AaronC81 I would love to see a PR to get search working with the Chrome URL bar.
