### ISSUE TITLE
When dark theme is enabled, light theme flickers visible when loading a page

### ISSUE THREAD

**Issue by AaronC81** [rubyapi/rubyapi#573]
When dark theme is enabled, each page seems to flicker from light theme to dark theme when first loading:

![clicking through several pages on the site, they each load in light theme then flick to dark theme after a couple of seconds](https://i.imgur.com/ioNfKhX.gif)

(This is on Chromium 85.0.4183.83 on Arch Linux.)

**Comment by natematykiewicz** [comment]
I've experienced this in Safari as well.

**Comment by natematykiewicz** [comment]
This still happens, even after reducing the JS size dramatically.

**Comment by colby-swandale** [comment]
This has been fixed with #642
