### ISSUE TITLE
Search results: Keyboard support

### ISSUE THREAD

**Issue by natematykiewicz** [rubyapi/rubyapi#588]
When I type in the quick search, I'd like to be able to arrow down to the first search result (and keep going for second, third, etc), and then press Enter (Return in Mac) to go to the page for the result (so, the same as if I clicked it).

<img width="1280" alt="Screen Shot 2020-10-19 at 9 37 01 PM" src="https://user-images.githubusercontent.com/5104186/96533315-4b4f3600-1253-11eb-9056-f3a4bc94fe1d.png">

**Comment by antoinesaliba** [comment]
+1

**Comment by AlexWayfer** [comment]
> +1

Please, use reactions for the issue (first comment), it's useful:

* There is a sorting by reactions
  ![image](https://user-images.githubusercontent.com/6510020/97322831-3e4ccb00-1881-11eb-896f-08532621db91.png)
* You don't disturb other subscribed people by this
* You can subscribe silently by separated button:
  ![image](https://user-images.githubusercontent.com/6510020/97322984-5fadb700-1881-11eb-8dbe-b6c96cf435aa.png)
