### ISSUE TITLE
Yanked version of `mimemagic` gem is pinned in `Gemfile.lock`

### ISSUE THREAD

**Issue by cstyles** [rubyapi/rubyapi#715]
When I run `bundle install` locally, I get this error:

```
Your bundle is locked to mimemagic (0.3.6), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the
author of mimemagic (0.3.6) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.6) that hasn't been removed in order to install.
```

It looks like the version of `mimemagic` that we depend on (0.3.6, as of #711) was yanked from rubygems.org.

Rubygem version list: https://rubygems.org/gems/mimemagic/versions
Relevant issue in mimemagic: https://github.com/mimemagicrb/mimemagic/issues/98
Discussion in rails: https://github.com/rails/rails/issues/41750

**Comment by natematykiewicz** [comment]
Yeah, it's quite the mess

https://github.com/rails/rails/issues/41750

https://github.com/rails/rails/issues/41757

**Comment by cstyles** [comment]
Yeah, I'm just getting up to speed on it now. I guess there's not much to do here but wait for it to be resolved. :\

**Comment by gareth** [comment]
> I guess there's not much to do here but wait for it to be resolved. :\

I jumped here from the linked issue, but you should now be able to run `bundle update mimemagic` and update to an MIT-licensed version of the gem (`0.3.8` or `0.4.1`).

This new version of the gem is missing a data file that caused the original licensing issue, but so long as that file is available elsewhere (by having the `shared-mime-info` package installed, for example) then as far as the maintainer is concerned the gem should work as expected.

**Comment by natematykiewicz** [comment]
One option is to simply stop installing `rails`, and instead just install the pieces that Ruby API actually uses. If you don't install `activestorage` or `actionmailbox`, then you won't transitively install `mimemagic`, and can just avoid the problem all together.

**Comment by colby-swandale** [comment]
I'm going to follow @natematykiewicz comment and only include the specific gems for bits of rails functionality we need until this mimemagic situation has been resolved.

**Comment by jbryan1112** [comment]
Change version of mimemagic to 0.3.10 in your Gemfile

Gemfile:
gem 'mimemagic', '~> 0.3.10'

**Comment by hortencia718** [comment]
not working for me can someone help 
i keep getting this message even after trying a few things that didn't work .. can someone help me figure this out 
error message below :
Your bundle is locked to mimemagic (0.3.5) from rubygems repository https://rubygems.org/ or
installed locally, but that version can no longer be found in that source. That means the
author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version
other than mimemagic (0.3.5) that hasn't been removed in order to install.

**Comment by jbryan1112** [comment]
This has been answered
https://stackoverflow.com/questions/66829141/heroku-push-rejected-error-failed-to-install-gems-via-bundler-probably-caused/66869930#66869930


Or find mimeemagic in your gems file and update or downgrade accordingly.
Read current status for mimemagic to know what to change version to.
