### ISSUE TITLE
Can't search for to_h, sort of.

### ISSUE THREAD

**Issue by tadman** [rubyapi/rubyapi#735]
You can search for "to_h", though you get nothing useful. Bizarrely if you then backspace delete the "h" the actual `to_h` search results appear.

---
Using Safari. No JavaScript errors reported.

**Comment by natematykiewicz** [comment]
Can you share a link to the search results or a screenshot of what you're referring to? I just typed "to_h" in the text box on the home page, pressed enter, and was sent to this page. https://rubyapi.org/3.0/o/s?q=to_h

The results are what I'd expect.

This was done on mobile Safari 14.

**Comment by natematykiewicz** [comment]
Oh, the autocomplete list is weird. I missed that.

![image](https://user-images.githubusercontent.com/5104186/115460998-8aecdf80-a1ee-11eb-9719-573193f46506.png)

![image](https://user-images.githubusercontent.com/5104186/115461013-8de7d000-a1ee-11eb-8774-da2b73f46e95.png)

**Comment by tadman** [comment]
Yeah, just noticed it's super wonky across the board. Just searched for "Open3" with the same weirdness.

**Comment by colby-swandale** [comment]
This has been resolved by #741
