### ISSUE TITLE
The table for `Process::clock_gettime` doesn't display properly

### ISSUE THREAD

**Issue by cstyles** [rubyapi/rubyapi#782]
Compare the tables here:
https://rubyapi.org/2.6/o/process#method-c-clock_gettime

With those here:
https://www.rubydoc.info/stdlib/core/Process:clock_gettime

It looks OK on mobile/vertical browsers, at least.

**Comment by colby-swandale** [comment]
Thanks for pointing this out. I can't think of a clean way to resolve this using the current desktop styles, so using the mobile UI is probably the best way forward.

**Comment by colby-swandale** [comment]
This has been resolved in #791
