### ISSUE TITLE
Elasticsearch blocking ruby-src doc import in development

### ISSUE THREAD

**Issue by colby-swandale** [rubyapi/rubyapi#849]
Running `./bin/rake import:ruby[..]` in development hangs forever and never completes due to something happening in Elastic Search when we reset the indexes here https://github.com/rubyapi/rubyapi/blob/2e961864aab8d412e751edfb063f69e47586b18b/lib/rubyapi_rdoc_generator.rb#L109

**Comment by natematykiewicz** [comment]
This might actually fix it:
https://github.com/rubyapi/rubyapi/pull/850
https://github.com/elastic/elasticsearch-rails/commit/5db9207ca398c5d77f671109360ca7f63e3f2112

**Comment by colby-swandale** [comment]
I was able to trace this back to an issue in the Faraday Async adapter. I'll remove them for now and open an issue at https://github.com/socketry/async-http-faraday
