### ISSUE TITLE
Overlapping inputs 

### ISSUE THREAD

**Issue by Maheshkumar-novice** [rubyapi/rubyapi#897]
![Bug](https://user-images.githubusercontent.com/67100964/134768799-dfe6a88e-b0af-435d-bf42-2fac7d67dc88.png)

Looks like something broken in the header part.

**Comment by natematykiewicz** [comment]
Are you still having this problem? I don't experience this.

If so, what browser?

**Comment by Maheshkumar-novice** [comment]
> Are you still having this problem? I don't experience this.
> 
> If so, what browser?

Sorry. I didn't tell the browser I used. It looks normal in chrome and firefox. I tried it in brave-browser.

**Comment by Maheshkumar-novice** [comment]
![Screenshot from 2021-09-28 07-50-14](https://user-images.githubusercontent.com/67100964/135011877-47e0a18c-0000-4bb0-bf10-f847dc96f5db.png)

![Screenshot from 2021-09-28 07-50-20](https://user-images.githubusercontent.com/67100964/135011883-f8d22537-13bb-418f-974c-5fe71f407d0d.png)

**Comment by natematykiewicz** [comment]
2.7.0 is not an option. https://rubyapi.org/2.7.0/o/string

The site only lets you do `major.minor`, not `major.minor.patch` because the patch versions do not have differences in methods -- they're simply bug fixes.

I could see the `2.7.*` redirecting to 2.7, but that's not an expected path and the UI does not provide it as an option.

**Comment by Maheshkumar-novice** [comment]
> 2.7.0 is not an option. https://rubyapi.org/2.7.0/o/string
> 
> The site only lets you do `major.minor`, not `major.minor.patch` because the patch versions do not have differences in methods -- they're simply bug fixes.
> 
> I could see the `2.7.*` redirecting to 2.7, but that's not an expected path and the UI does not provide it as an option.

Thank you for taking time to explain.

**Comment by natematykiewicz** [comment]
No problem

**Comment by Maheshkumar-novice** [comment]
I will close the issue now.
